# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161111_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('pubDate', models.DateField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('price', models.IntegerField(max_length=128)),
            ],
        ),
    ]
