# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20161111_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-pubDateTime',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
